// ======================================================================
// \title  PassiveTextLoggerComponentAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PassiveTextLogger component base class
// ======================================================================

#include <cstdio>

#include "F-Prime/Svc/PassiveConsoleTextLogger/PassiveTextLoggerComponentAc.hpp"
#include "Fw/Types/Assert.hpp"
#if FW_ENABLE_TEXT_LOGGING
#include "Fw/Types/String.hpp"
#endif

namespace Svc {

  // ----------------------------------------------------------------------
  // Component initialization
  // ----------------------------------------------------------------------

  void PassiveTextLoggerComponentBase ::
    init(NATIVE_INT_TYPE instance)
  {
    // Initialize base class
    Fw::PassiveComponentBase::init(instance);

    // Connect input port TextLogger
    for (
      PlatformIntType port = 0;
      port < static_cast<PlatformIntType>(this->getNum_TextLogger_InputPorts());
      port++
    ) {
      this->m_TextLogger_InputPort[port].init();
      this->m_TextLogger_InputPort[port].addCallComp(
        this,
        m_p_TextLogger_in
      );
      this->m_TextLogger_InputPort[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      char portName[120];
      (void) snprintf(
        portName,
        sizeof(portName),
        "%s_TextLogger_InputPort[%" PRI_PlatformIntType "]",
        this->m_objName,
        port
      );
      this->m_TextLogger_InputPort[port].setObjName(portName);
#endif
    }
  }

  // ----------------------------------------------------------------------
  // Getters for typed input ports
  // ----------------------------------------------------------------------

  Fw::InputLogTextPort* PassiveTextLoggerComponentBase ::
    get_TextLogger_InputPort(NATIVE_INT_TYPE portNum)
  {
    FW_ASSERT(
      portNum < this->getNum_TextLogger_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_TextLogger_InputPort[portNum];
  }

  // ----------------------------------------------------------------------
  // Component construction and destruction
  // ----------------------------------------------------------------------

  PassiveTextLoggerComponentBase ::
    PassiveTextLoggerComponentBase(const char* compName) :
      Fw::PassiveComponentBase(compName)
  {

  }

  PassiveTextLoggerComponentBase ::
    ~PassiveTextLoggerComponentBase()
  {

  }

  // ----------------------------------------------------------------------
  // Getters for numbers of typed input ports
  // ----------------------------------------------------------------------

  NATIVE_INT_TYPE PassiveTextLoggerComponentBase ::
    getNum_TextLogger_InputPorts() const
  {
    return static_cast<NATIVE_INT_TYPE>(FW_NUM_ARRAY_ELEMENTS(this->m_TextLogger_InputPort));
  }

  // ----------------------------------------------------------------------
  // Port handler base-class functions for typed input ports
  //
  // Call these functions directly to bypass the corresponding ports
  // ----------------------------------------------------------------------

  void PassiveTextLoggerComponentBase ::
    TextLogger_handlerBase(
        NATIVE_INT_TYPE portNum,
        FwEventIdType id,
        Fw::Time& timeTag,
        const Fw::LogSeverity& severity,
        Fw::TextLogString& text
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      portNum < this->getNum_TextLogger_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    // Down call to pure virtual handler method implemented in Impl class
    this->TextLogger_handler(
      portNum,
      id,
      timeTag,
      severity,
      text
    );
  }

  // ----------------------------------------------------------------------
  // Calls for messages received on typed input ports
  // ----------------------------------------------------------------------

  void PassiveTextLoggerComponentBase ::
    m_p_TextLogger_in(
        Fw::PassiveComponentBase* callComp,
        NATIVE_INT_TYPE portNum,
        FwEventIdType id,
        Fw::Time& timeTag,
        const Fw::LogSeverity& severity,
        Fw::TextLogString& text
    )
  {
    FW_ASSERT(callComp);
    PassiveTextLoggerComponentBase* compPtr = static_cast<PassiveTextLoggerComponentBase*>(callComp);
    compPtr->TextLogger_handlerBase(
      portNum,
      id,
      timeTag,
      severity,
      text
    );
  }

}
