# CMake generated Testfile for 
# Source directory: /Users/heron/Desktop/memedir/memesat-1.local/Drv/Ip
# Build directory: /Users/heron/Desktop/memedir/memesat-1.local/Ref/build-fprime-automatic-native-ut/F-Prime/Drv/Ip
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Drv_Ip_Tcp_test "/Users/heron/Desktop/memedir/memesat-1.local/Ref/build-fprime-automatic-native-ut/bin/Darwin/Drv_Ip_Tcp_test")
set_tests_properties(Drv_Ip_Tcp_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/heron/Desktop/memedir/memesat-1.local/cmake/target/ut.cmake;90;add_test;/Users/heron/Desktop/memedir/memesat-1.local/cmake/target/target.cmake;93;ut_add_module_target;/Users/heron/Desktop/memedir/memesat-1.local/cmake/target/target.cmake;93;cmake_language;/Users/heron/Desktop/memedir/memesat-1.local/cmake/target/target.cmake;132;setup_single_target;/Users/heron/Desktop/memedir/memesat-1.local/cmake/module.cmake;40;setup_module_targets;/Users/heron/Desktop/memedir/memesat-1.local/cmake/module.cmake;98;generate_base_module_properties;/Users/heron/Desktop/memedir/memesat-1.local/cmake/API.cmake;471;generate_ut;/Users/heron/Desktop/memedir/memesat-1.local/Drv/Ip/CMakeLists.txt;44;register_fprime_ut;/Users/heron/Desktop/memedir/memesat-1.local/Drv/Ip/CMakeLists.txt;0;")
add_test(Drv_Ip_Udp_test "/Users/heron/Desktop/memedir/memesat-1.local/Ref/build-fprime-automatic-native-ut/bin/Darwin/Drv_Ip_Udp_test")
set_tests_properties(Drv_Ip_Udp_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/heron/Desktop/memedir/memesat-1.local/cmake/target/ut.cmake;90;add_test;/Users/heron/Desktop/memedir/memesat-1.local/cmake/target/target.cmake;93;ut_add_module_target;/Users/heron/Desktop/memedir/memesat-1.local/cmake/target/target.cmake;93;cmake_language;/Users/heron/Desktop/memedir/memesat-1.local/cmake/target/target.cmake;132;setup_single_target;/Users/heron/Desktop/memedir/memesat-1.local/cmake/module.cmake;40;setup_module_targets;/Users/heron/Desktop/memedir/memesat-1.local/cmake/module.cmake;98;generate_base_module_properties;/Users/heron/Desktop/memedir/memesat-1.local/cmake/API.cmake;471;generate_ut;/Users/heron/Desktop/memedir/memesat-1.local/Drv/Ip/CMakeLists.txt;49;register_fprime_ut;/Users/heron/Desktop/memedir/memesat-1.local/Drv/Ip/CMakeLists.txt;0;")
