// ======================================================================
// \title  LinuxTimerComponentAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for LinuxTimer component base class
// ======================================================================

#ifndef Svc_LinuxTimerComponentAc_HPP
#define Svc_LinuxTimerComponentAc_HPP

#include "FpConfig.hpp"
#include "Fw/Comp/ActiveComponentBase.hpp"
#include "Fw/Port/InputSerializePort.hpp"
#include "Fw/Port/OutputSerializePort.hpp"
#include "Svc/Cycle/CyclePortAc.hpp"

namespace Svc {

  //! \class LinuxTimerComponentBase
  //! \brief Auto-generated base for LinuxTimer component
  //!
  //! A Linux interval timer
  class LinuxTimerComponentBase :
    public Fw::PassiveComponentBase
  {

      // ----------------------------------------------------------------------
      // Friend classes
      // ----------------------------------------------------------------------

      //! Friend class for white-box testing
      friend class LinuxTimerComponentBaseFriend;

    PROTECTED:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      //! Enumerations for numbers of typed output ports
      enum {
        NUM_CYCLEOUT_OUTPUT_PORTS = 1,
      };

    public:

      // ----------------------------------------------------------------------
      // Component initialization
      // ----------------------------------------------------------------------

      //! Initialize LinuxTimerComponentBase object
      void init(
          NATIVE_INT_TYPE instance = 0 //!< The instance number
      );

    public:

      // ----------------------------------------------------------------------
      // Connect typed input ports to typed output ports
      // ----------------------------------------------------------------------

      //! Connect port to CycleOut[portNum]
      void set_CycleOut_OutputPort(
          NATIVE_INT_TYPE portNum, //!< The port number
          Svc::InputCyclePort* port //!< The input port
      );

#if FW_PORT_SERIALIZATION

    public:

      // ----------------------------------------------------------------------
      // Connect serial input ports to typed output ports
      // ----------------------------------------------------------------------

      //! Connect port to CycleOut[portNum]
      void set_CycleOut_OutputPort(
          NATIVE_INT_TYPE portNum, //!< The port number
          Fw::InputSerializePort* port //!< The port
      );

#endif

    PROTECTED:

      // ----------------------------------------------------------------------
      // Component construction and destruction
      // ----------------------------------------------------------------------

      //! Construct LinuxTimerComponentBase object
      LinuxTimerComponentBase(
          const char* compName = "" //!< The component name
      );

      //! Destroy LinuxTimerComponentBase object
      virtual ~LinuxTimerComponentBase();

    PROTECTED:

      // ----------------------------------------------------------------------
      // Getters for numbers of typed output ports
      // ----------------------------------------------------------------------

      //! Get the number of CycleOut output ports
      //!
      //! \return The number of CycleOut output ports
      NATIVE_INT_TYPE getNum_CycleOut_OutputPorts() const;

    PROTECTED:

      // ----------------------------------------------------------------------
      // Connection status queries for typed output ports
      // ----------------------------------------------------------------------

      //! Check whether port CycleOut is connected
      //!
      //! \return Whether port CycleOut is connected
      bool isConnected_CycleOut_OutputPort(
          NATIVE_INT_TYPE portNum //!< The port number
      );

    PROTECTED:

      // ----------------------------------------------------------------------
      // Invocation functions for typed output ports
      // ----------------------------------------------------------------------

      //! Invoke output port CycleOut
      void CycleOut_out(
          NATIVE_INT_TYPE portNum, //!< The port number
          Svc::TimerVal& cycleStart //!< Cycle start timer value
      );

    PRIVATE:

      // ----------------------------------------------------------------------
      // Typed output ports
      // ----------------------------------------------------------------------

      //! Output port CycleOut
      Svc::OutputCyclePort m_CycleOut_OutputPort[NUM_CYCLEOUT_OUTPUT_PORTS];

  };

}

#endif
