
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/heron/Library/Python/3.9/lib/python/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Darwin - 22.6.0 - arm64
...
