// ======================================================================
// \title  SignalTypeEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for SignalType enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "Ref/SignalGen/SignalTypeEnumAc.hpp"

namespace Ref {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  SignalType& SignalType ::
    operator=(const SignalType& obj)
  {
    this->e = obj.e;
    return *this;
  }

  SignalType& SignalType ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const SignalType& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool SignalType ::
    isValid() const
  {
    return ((e >= TRIANGLE) && (e <= NOISE));
  }

  Fw::SerializeStatus SignalType ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus SignalType ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void SignalType ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case TRIANGLE:
        s = "TRIANGLE";
        break;
      case SQUARE:
        s = "SQUARE";
        break;
      case SINE:
        s = "SINE";
        break;
      case NOISE:
        s = "NOISE";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void SignalType ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
